/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package view;

/**
 *
 * @author ASUS_PC
 */
public class InfoDisplayPanel extends javax.swing.JPanel {

    /**
     * Creates new form InfoDisplayPanel
     */
    public InfoDisplayPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jTextField8 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jTextField9 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jTextField10 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jTextField11 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jTextField12 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jTextField13 = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();

        setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Your Information");
        add(jLabel1);
        jLabel1.setBounds(134, 11, 158, 22);

        jLabel2.setText("First Name:");
        add(jLabel2);
        jLabel2.setBounds(27, 54, 55, 14);

        jTextField1.setText(" ");
        jTextField1.setEnabled(false);
        add(jTextField1);
        jTextField1.setBounds(144, 51, 88, 20);

        jLabel3.setText("Last Name:");
        add(jLabel3);
        jLabel3.setBounds(250, 54, 54, 14);

        jTextField2.setText(" ");
        jTextField2.setEnabled(false);
        add(jTextField2);
        jTextField2.setBounds(314, 51, 88, 20);

        jLabel4.setText("Date of Birth:");
        add(jLabel4);
        jLabel4.setBounds(27, 85, 65, 14);

        jTextField3.setText(" ");
        jTextField3.setEnabled(false);
        add(jTextField3);
        jTextField3.setBounds(144, 82, 135, 20);

        jLabel5.setText("Gender:");
        add(jLabel5);
        jLabel5.setBounds(27, 111, 39, 14);

        jTextField4.setText(" ");
        jTextField4.setEnabled(false);
        add(jTextField4);
        jTextField4.setBounds(144, 108, 62, 20);

        jLabel6.setText("Contact Details:");
        add(jLabel6);
        jLabel6.setBounds(27, 142, 77, 14);

        jTextField5.setText(" ");
        jTextField5.setEnabled(false);
        add(jTextField5);
        jTextField5.setBounds(144, 139, 303, 20);

        jLabel7.setText("Email:");
        add(jLabel7);
        jLabel7.setBounds(27, 173, 28, 14);

        jTextField6.setText(" ");
        jTextField6.setEnabled(false);
        add(jTextField6);
        jTextField6.setBounds(144, 170, 303, 20);

        jLabel9.setText("Address:");
        add(jLabel9);
        jLabel9.setBounds(27, 204, 43, 14);

        jTextField8.setText(" ");
        jTextField8.setEnabled(false);
        add(jTextField8);
        jTextField8.setBounds(144, 201, 303, 20);

        jLabel8.setText("Education Qualification:");
        add(jLabel8);
        jLabel8.setBounds(27, 235, 113, 14);

        jTextField9.setText(" ");
        jTextField9.setEnabled(false);
        add(jTextField9);
        jTextField9.setBounds(144, 232, 303, 20);

        jLabel10.setText("Marital Status:");
        add(jLabel10);
        jLabel10.setBounds(27, 261, 70, 14);

        jTextField10.setText(" ");
        jTextField10.setEnabled(false);
        add(jTextField10);
        jTextField10.setBounds(144, 258, 303, 20);

        jLabel11.setText("Addess Proof:");
        add(jLabel11);
        jLabel11.setBounds(27, 287, 68, 14);

        jTextField11.setText(" ");
        jTextField11.setEnabled(false);
        add(jTextField11);
        jTextField11.setBounds(144, 284, 303, 20);

        jLabel12.setText("Citizen Proof:");
        add(jLabel12);
        jLabel12.setBounds(27, 313, 65, 14);

        jTextField12.setText(" ");
        jTextField12.setEnabled(false);
        add(jTextField12);
        jTextField12.setBounds(144, 310, 303, 20);

        jLabel13.setText("Physical Health:");
        add(jLabel13);
        jLabel13.setBounds(30, 340, 76, 14);

        jTextField13.setText(" ");
        jTextField13.setEnabled(false);
        add(jTextField13);
        jTextField13.setBounds(144, 336, 303, 20);

        jLabel14.setText("jLabel14");
        add(jLabel14);
        jLabel14.setBounds(30, 370, 40, 14);

        jButton1.setText("Back");
        add(jButton1);
        jButton1.setBounds(342, 534, 105, 44);

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/green-design.png"))); // NOI18N
        add(jLabel15);
        jLabel15.setBounds(0, 0, 470, 600);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField13;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    // End of variables declaration//GEN-END:variables
}
