/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package view;

import control.DateLabelFormatter;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import net.sourceforge.jdatepicker.impl.JDatePanelImpl;
import net.sourceforge.jdatepicker.impl.JDatePickerImpl;
import net.sourceforge.jdatepicker.impl.UtilDateModel;

/**
 *
 * @author ASUS_PC
 */
public class RegisterPanel extends javax.swing.JPanel {
    private JDatePickerImpl datePicker;
    /**
     * Creates new form RegisterPanel
     */
    public RegisterPanel() {
        initComponents();
        UtilDateModel model = new UtilDateModel();
        model.setDate(1990, 8, 24);
        model.setSelected(true);

//		UtilCalendarModel model = new UtilCalendarModel();
//		SqlDateModel model = new SqlDateModel();
        JDatePanelImpl datePanel = new JDatePanelImpl(model);

//		datePicker = new JDatePickerImpl(datePanel);
        datePicker = new JDatePickerImpl(datePanel, new DateLabelFormatter());

        this.birthdayPanel.add(datePicker);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        buttonGroup5 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        tfFName = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        tfLName = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        rdoGMale = new javax.swing.JRadioButton();
        rdoGFemale = new javax.swing.JRadioButton();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        taContact = new javax.swing.JTextArea();
        jLabel7 = new javax.swing.JLabel();
        tfEmail = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        tfEducation = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        tfOccupation = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        rdoMMarried = new javax.swing.JRadioButton();
        rdoMSingle = new javax.swing.JRadioButton();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        rdoPhNormal = new javax.swing.JRadioButton();
        rdoPhHandicapped = new javax.swing.JRadioButton();
        btnSubmit = new javax.swing.JButton();
        btnReset = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        tfMName = new javax.swing.JTextField();
        rdoAdYes = new javax.swing.JRadioButton();
        rdoAdNo = new javax.swing.JRadioButton();
        rdoCiYes = new javax.swing.JRadioButton();
        rdoCiNo = new javax.swing.JRadioButton();
        birthdayPanel = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        taAddress = new javax.swing.JTextArea();

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Register Form");

        jLabel2.setText("First Name:");

        jLabel3.setText("Last Name:");

        tfLName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfLNameActionPerformed(evt);
            }
        });

        jLabel4.setText("Date of Birth:");

        jLabel5.setText("Gender");

        buttonGroup1.add(rdoGMale);
        rdoGMale.setText("Male");

        buttonGroup1.add(rdoGFemale);
        rdoGFemale.setText("Female");

        jLabel6.setText("Contact Details:");

        taContact.setColumns(20);
        taContact.setRows(5);
        jScrollPane1.setViewportView(taContact);

        jLabel7.setText("Email:");

        jLabel8.setText("Address:");

        jLabel9.setText("Education Qualification:");

        jLabel10.setText("Occupation:");

        jLabel11.setText("Marital Status:");

        buttonGroup2.add(rdoMMarried);
        rdoMMarried.setText("Married");

        buttonGroup2.add(rdoMSingle);
        rdoMSingle.setText("Single");

        jLabel12.setText("Address Proof:");

        jLabel13.setText("Citizen Proof:");

        jLabel14.setText("Physical Health:");

        buttonGroup5.add(rdoPhNormal);
        rdoPhNormal.setText("Normal");

        buttonGroup5.add(rdoPhHandicapped);
        rdoPhHandicapped.setText("Handicapped");

        btnSubmit.setText("Submit");
        btnSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitActionPerformed(evt);
            }
        });

        btnReset.setText("Reset");
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });

        jLabel15.setText("Mid Name :");

        buttonGroup3.add(rdoAdYes);
        rdoAdYes.setText("Yes");

        buttonGroup3.add(rdoAdNo);
        rdoAdNo.setText("No");

        buttonGroup4.add(rdoCiYes);
        rdoCiYes.setText("Yes");

        buttonGroup4.add(rdoCiNo);
        rdoCiNo.setText("No");

        taAddress.setColumns(20);
        taAddress.setRows(5);
        jScrollPane2.setViewportView(taAddress);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnSubmit, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(94, 94, 94)
                .addComponent(btnReset, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(129, 129, 129))
            .addGroup(layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10)
                            .addComponent(jLabel11)
                            .addComponent(jLabel12)
                            .addComponent(jLabel13)
                            .addComponent(jLabel14)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel6)
                                .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING))
                            .addComponent(jLabel8))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rdoCiYes)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(rdoGMale)
                                .addGap(18, 18, 18)
                                .addComponent(rdoGFemale))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(tfOccupation, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(tfEducation, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 215, Short.MAX_VALUE)
                                .addComponent(tfEmail, javax.swing.GroupLayout.Alignment.LEADING))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(rdoMMarried)
                                    .addComponent(rdoAdYes)
                                    .addComponent(rdoPhNormal))
                                .addGap(29, 29, 29)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(rdoPhHandicapped, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(rdoAdNo)
                                    .addComponent(rdoMSingle)
                                    .addComponent(rdoCiNo))))
                        .addGap(68, 68, 68))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tfFName, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(21, 21, 21)
                        .addComponent(jLabel15)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tfMName, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tfLName, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(44, 44, 44))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(57, 57, 57)
                        .addComponent(birthdayPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGap(194, 194, 194)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tfFName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(tfMName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15)
                    .addComponent(tfLName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(birthdayPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(rdoGMale)
                    .addComponent(rdoGFemale))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jLabel6))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(jLabel7))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel8)))
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(tfEducation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addComponent(tfOccupation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(rdoMMarried)
                    .addComponent(rdoMSingle))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(rdoAdYes)
                    .addComponent(rdoAdNo))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rdoCiYes)
                    .addComponent(rdoCiNo)
                    .addComponent(jLabel13))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(rdoPhNormal)
                    .addComponent(rdoPhHandicapped))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnReset, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSubmit, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void tfLNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfLNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfLNameActionPerformed

    private void btnSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitActionPerformed
        // TODO add your handling code here:
        if(!checkInputForm().equalsIgnoreCase("Information Input Register\n------------------------------\n")){
            showMessage(checkInputForm());
        }
        else{
            String strInfo = confirmInfo();
            if(checkEmail(tfEmail.getText().trim()) ==  true && checkInputForm().equalsIgnoreCase("Information Input Register\n------------------------------\n")){
                int confirm = showMessageConfirm(strInfo);
                if(confirm == JOptionPane.YES_OPTION){
                    insertDatabase();
                }
            }
        }
        
    }//GEN-LAST:event_btnSubmitActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        tfFName.setText("");
        tfLName.setText("");
        tfMName.setText("");
        taContact.setText("");
        taAddress.setText("");
        tfEmail.setText("");
        tfEducation.setText("");
        tfOccupation.setText("");
        buttonGroup1.clearSelection();
        buttonGroup2.clearSelection();
        buttonGroup3.clearSelection();
        buttonGroup4.clearSelection();
        buttonGroup5.clearSelection();

    }//GEN-LAST:event_btnResetActionPerformed

    public void showMessage(String msg) {
        JOptionPane.showMessageDialog(this, msg);
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel birthdayPanel;
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnSubmit;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.ButtonGroup buttonGroup5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JRadioButton rdoAdNo;
    private javax.swing.JRadioButton rdoAdYes;
    private javax.swing.JRadioButton rdoCiNo;
    private javax.swing.JRadioButton rdoCiYes;
    private javax.swing.JRadioButton rdoGFemale;
    private javax.swing.JRadioButton rdoGMale;
    private javax.swing.JRadioButton rdoMMarried;
    private javax.swing.JRadioButton rdoMSingle;
    private javax.swing.JRadioButton rdoPhHandicapped;
    private javax.swing.JRadioButton rdoPhNormal;
    private javax.swing.JTextArea taAddress;
    private javax.swing.JTextArea taContact;
    private javax.swing.JTextField tfEducation;
    private javax.swing.JTextField tfEmail;
    private javax.swing.JTextField tfFName;
    private javax.swing.JTextField tfLName;
    private javax.swing.JTextField tfMName;
    private javax.swing.JTextField tfOccupation;
    // End of variables declaration//GEN-END:variables

    private String checkInputForm() {
        String msg = "Information Input Register\n------------------------------\n";
        if(tfFName.getText().trim().isEmpty()){
            msg +="\n\nFirst Name must not Null";
        }
        if(tfLName.getText().trim().isEmpty()){
            msg +="\nLast Name must not Null";
        }
        if(tfEmail.getText().trim().isEmpty()){
            msg +="\nEmail must not Null";
        }
        if(taAddress.getText().trim().isEmpty()){
            msg +="\nAddress must not Null";
        }
        if(tfEducation.getText().trim().isEmpty()){
            msg +="\nEducation Qualification must not Null";
        }
        if(tfOccupation.getText().trim().isEmpty()){
            msg +="\nOccupation must not Null";
        }
        if(buttonGroup1.getSelection() == null){
            msg+="\nGender must choise";
        }
        if(buttonGroup2.getSelection() == null){
            msg+="\nMarital Status must choise";
        }
        if(buttonGroup3.getSelection() == null){
            msg+="\nAddress Proof must choise";
        }
        if(buttonGroup4.getSelection() == null){
            msg+="\nCitizen Proof must choise";
        }
        if(buttonGroup5.getSelection() == null){
            msg+="\nPhysical Health must choise";
        }
        return msg;
    }

    private String confirmInfo() {
        String msg = "Information Input Register\n------------------------------\n";
        String msg2 ="";
        if(checkInput(tfFName.getText().trim()) == true){
            msg +="\n\nFirst Name :"+tfFName.getText().trim();
        }
        else{
            msg2 += "\nFirst Name : Not match!";
        }
        if(!tfMName.getText().trim().isEmpty()){
            if(checkInput(tfMName.getText().trim()) == true){
                    msg +="\nMid Name :"+tfMName.getText().trim();
            }
            else{
                msg2 += "\nMid Name : Not match!";
            }
        }
        if(checkInput(tfLName.getText().trim()) == true){
            msg +="\nLast Name :"+tfLName.getText().trim();
        }
        else{
            msg2 += "\nLast Name : Not match!";
        }
        
            
        //Date if Birth
        
        
        
        if(rdoGMale.isSelected()){
            msg+="\nGender : Male";
        }
        else if(rdoGFemale.isSelected()){
            msg+="\nGender : FeMale";
        }
        
        
        if(!taContact.getText().trim().isEmpty()){
            msg +="\nContact Details :"+taContact.getText().trim();
        }
        if(checkEmail(tfEmail.getText().trim()) !=  true){
            msg2 +="\nEmail Not Match !\nExample:\nEmail : abc1234@gmail.com";
        }
        else{
            msg +="\nEmail :"+tfEmail.getText().trim();
        }
        msg +="\nAddress :"+taAddress.getText().trim();
        msg +="\nEducation Qualification :"+tfEducation.getText().trim();
        msg +="\nOccupation :"+tfOccupation.getText().trim();
        
        if(rdoMMarried.isSelected()){
            msg+="\nMarital Status : Married";
        }
        else if(rdoMSingle.isSelected()){
            msg+="\nMarital Status : Single";
        }
        if(rdoAdYes.isSelected()){
            msg+="\nAddress Proof : Yes";
        }
        else if(rdoAdNo.isSelected()){
            msg+="\nAddress Proof : No";
        }
        if(rdoCiYes.isSelected()){
            msg+="\nCitizen Proof : Yes";
        }
        else if(rdoCiNo.isSelected()){
            msg+="\nCitizen Proof : No";
        }
        if(rdoPhHandicapped.isSelected()){
            msg+="\nPhysical Health : Normal";
        }
        else if(rdoPhNormal.isSelected()){
            msg+="\nPhysical Health : Handicapped";
        }
        if(!msg2.isEmpty()){
            showMessage(msg2);
            msg = "Information Input Register\n------------------------------\n";
        }
        return msg;
    }

    private int showMessageConfirm(String confirmInfo) {
        int confirm = JOptionPane.showConfirmDialog(this, confirmInfo, "", JOptionPane.OK_CANCEL_OPTION);
        return confirm;
    }

    private void insertDatabase() {
//        PersonDetailsDAO pDao = new PersonDetailsDao();
//        ClientFrame.remoteObject.sendRequest(null, WIDTH);
    }

    private boolean checkEmail(String email) {
        boolean check = false;
        Pattern pat;
        Matcher match;
        pat = Pattern.compile("^[a-zA-Z]\\w+[@]\\w+[.]\\w+[.]?\\w+$");
        match = pat.matcher(email);
        if(match.find()){
            check =  true;
        }
        return check;
    }
    private boolean checkInput(String str) {
        boolean check = false;
        Pattern pat;
        Matcher match;
        pat = Pattern.compile("^[a-zA-Z]\\w+$");
        match = pat.matcher(str);
        if(match.find()){
            check =  true;
        }
        System.out.println(check);
        return check;
    }
}
